/*
 *  ubit.h: includes all common Ubit headers 
 *  Ubit GUI Toolkit - Version 8
 *  (C) 2018 Chris Daley
 *  (C) 2009 | Eric Lecolinet | TELECOM ParisTech | http://www.enst.fr/~elc/ubit
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 * 
 */


#ifndef _ubit_hpp_
#define	_ubit_hpp_ 1

// udefs.hpp includes <ubit/ubit_features.h> that defines defines crucial compilation options
// and is generated by 'configure' or 'umake' (which are in the Ubit base directory).
#include <ubit/udefs.hpp>
#include <ubit/core/object.h>
#include <ubit/core/node.h>
#include <ubit/core/length.h>
#include <ubit/ugeom.hpp>
#include <ubit/core/number.h>

#include <ubit/core/attribute.h>
#include <ubit/uboxgeom.hpp>
#include <ubit/uborder.hpp>
#include <ubit/ui/background.h>
#include <ubit/ucolor.hpp>
#include <ubit/ucursor.hpp>
#include <ubit/uedit.hpp>
#include <ubit/draw/font.h>

#include <ubit/uon.hpp>
#include <ubit/ucall.hpp>

#include <ubit/core/data.h>
#include <ubit/core/string.h>
#include <ubit/usymbol.hpp>
#include <ubit/uima.hpp>
#include <ubit/upix.hpp>

#include <ubit/core/element.h>
#include <ubit/ui/box.h>
#include <ubit/uboxes.hpp>
#include <ubit/ui/window.h>
#include <ubit/udialogs.hpp>
#include <ubit/ui/menu.h>
#include <ubit/ui/control-menu.h>
#include <ubit/ui/interactors.h>
#include <ubit/uscrollpane.hpp>
#include <ubit/uscrollbar.hpp>
#include <ubit/uslider.hpp>
#include <ubit/utable.hpp>
#include <ubit/uchoice.hpp>
#include <ubit/ufilebox.hpp>
#include <ubit/ulistbox.hpp>
#include <ubit/upalette.hpp>
#include <ubit/utreebox.hpp>

#include <ubit/uzoom.hpp>
#include <ubit/uglcanvas.hpp>
#include <ubit/u3d.hpp>

#include <ubit/core/application.h>
#include <ubit/ui/display.h>
#include <ubit/core/event.h>
#include <ubit/ukey.hpp>
#include <ubit/ui/view.h>
#include <ubit/ufontmetrics.hpp>
#include <ubit/uupdate.hpp>
#include <ubit/ui/updatecontext.h>
#include <ubit/ugraph.hpp>
#include <ubit/core/config.h>
#include <ubit/ustyle.hpp>
#include <ubit/utimer.hpp>
#include <ubit/usource.hpp>
#include <ubit/ueventflow.hpp>
#include <ubit/selection.hpp>
#include <ubit/ufile.hpp>

#endif

