/* Generated by configure.  Do not edit */
#ifndef UBIT_FEATURES_H
#define UBIT_FEATURES_H

#ifndef ubit_public
#define ubit_public
#endif

#define UBIT_VERSION_MAJOR 6
#define UBIT_VERSION_MINOR 1
#define UBIT_VERSION_MICRO 0
#define UBIT_VERSION "6.1.0"

/* Features */
#define	UBIT_WITH_X11 1
#define	UBIT_WITH_GL 1
#define	UBIT_WITH_FREETYPE 1
#define	UBIT_WITH_JPEG 1
#define	UBIT_WITH_XPM 1
#define	UBIT_WITH_GIF 1


#endif // UBIT_FEATURES_H
