/* ***********************************************************************
 *
 *  udefs.hpp: declaration of the main Ubit classes 
 *  Ubit GUI Toolkit - Version 6
 *  (C) 2009 | Eric Lecolinet | TELECOM ParisTech | http://www.enst.fr/~elc/ubit
 *
 * ***********************************************************************
 * COPYRIGHT NOTICE : 
 * THIS PROGRAM IS DISTRIBUTED WITHOUT ANY WARRANTY AND WITHOUT EVEN THE 
 * IMPLIED WARRANTY OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. 
 * YOU CAN REDISTRIBUTE IT AND/OR MODIFY IT UNDER THE TERMS OF THE GNU 
 * GENERAL PUBLIC LICENSE AS PUBLISHED BY THE FREE SOFTWARE FOUNDATION; 
 * EITHER VERSION 2 OF THE LICENSE, OR (AT YOUR OPTION) ANY LATER VERSION.
 * SEE FILES 'COPYRIGHT' AND 'COPYING' FOR MORE DETAILS.
 * ***********************************************************************/

#ifndef _udefs_hpp_
#define	_udefs_hpp_ 1

#include <string>
#include <vector>
#include <list>

// <ubit/ubit_features.h> defines crucial compilation options. It is automatically 
// generated by 'configure' or 'umake' (which are in the Ubit base directory).
#include <ubit/ubit_features.h>

#define UBIT5 (UBIT_VERSION_MAJOR >= 5)
#define UBIT6 (UBIT_VERSION_MINOR >= 6)
#define null nullptr

namespace ubit {

  typedef char Char;

  class Object;     // base class of all objects
  class Node;       // base class of all objects that can be added to the scene graph
  
  // elements (groups, boxes and widgets)
  
  class Element;    // base class of element nodes (derives from Node)
  class Box;
  class Label;
  class Button;
  class Item;
  class TextField;
  class TextArea;
  class FlowBox;
  class CardBox;
  class ComboBox;
  class ListBox;
  class AlertBox;
  class FileChooser;
  class DocumentBox;
  class TreeBox;
  class TreeNode;
  class Palette;
  class Slider;
  class ScrollBar;
  class ScrollPane;
  class ZoomPane;
  class Table;
  class Document;
  class GLCanvas;
  
  // windows and menus (derive from Box)
  
  class Window;
  class Frame;
  class Dialog;
  class MenuBar;
  class Menu;
  class PopupMenu;
  class PieMenu;
  class ControlMenu;
  class SubWindow;
  
  // 3D widgets (derive from Box)
  
  class U3Dcanvas;
  class U3Dbox;
  class U3Dwin;
  
  // data (strings, images, pixmaps, symbols)
  
  class Data;     // base class of data nodes (derives from Node)
  class String;
  class Image;
  class UPix;
  class Symbol;
  
  // attributes
  
  class Attribute;  // base class of attributes nodes (derives from Node)
  class AttributeList;
  class UCall;       // callback objects
  class Color;
  class Alpha;
  class Background;
  class Border;
  class Font;
  class FontFamily;
  class FontMetrics;
  class FontDescription;
  class Position;
  class U3Dpos;
  class Scale;
  class Size;
  class Padding;
  class Orientation;
  class HAlign;
  class VAlign;
  class HSpacing;
  class VSpacing;
  class Cursor;
  class Choice;
  class TextEdit;

  // application, display and global configuration
  
  class Application;
  class Display;
  class UConf;
  class Option;
  class Selection;

  // event conditions
  
  class Condition;
  class UOn;
  class Flag;
  class UFlagdef;
  class UPropdef;
  
  // events

  class Event;
  class InputEvent;
  class MouseEvent;
  class KeyEvent;
  class UWheelEvent;
  class UViewEvent;
  class PaintEvent;
  class UResizeEvent;
  class UWinEvent;
  class UserEvent;
  class MessageEvent;
  class TimerEvent;  
  class USysWMEvent;

  class EventFlow;
  
  class Key;  // key codes
  class Modifier;  // modifier masks
   
  // geometry
  
  class Unit;
  class Length;
  class Point;
  class Dimension;
  class Shape;
  class Line;
  class Rectangle;
  class Ellipse;
  class Arc;
  class Polygon;
  
  // graphics & rendering
  
  class Graph;
  class Rgba;
  class Update;
  class RenderContext;
  class GLContext;
  
  // errors
  
  class Error;
  class ErrorHandler;
  
  // numbers
  
  class Int;
  class Float;
  class Double;
  
  // metaclasses
  
  class Class;
  
  // view and styles
  
  class View;
  class ViewStyle;
  class Style;
  class StyleSheet;

  // arglists
  
  class Args;
  class Child;
  class Parent;
  
  // file and network
  
  class FileInfo;
  class UFileDir;
  class Socket;
  class Source;
  class Timer;
  class Message;
  class MessagePort;
  class MessagePortMap;
  class MessageService;
  
  // implementation
  
  class UpdateContext;
  class WindowUpdateContext;
  class UBehavior;
  class UWinImpl;
  class USoftwinImpl;
  class UHardwinImpl;
  class UHardIma;
  class UHardPix;
  class UHardFont;
  
}

#endif
