#!/bin/bash
printf "# Automatically generated by scripts/list-files.sh\n" > cmake/core-files.cmake
printf "set(UBIT_CORE_FILES\n" >> cmake/core-files.cmake
shopt -s globstar
for file in src/ubit/**; do
	if [ ${file: -4} == ".cpp" ]
	then
		printf "\t%s\n" $file >> cmake/core-files.cmake
	fi
done;
echo ")" >> cmake/core-files.cmake
