# This file is generated. Do not edit. Regenerate this with scripts/generate-cmake-files.js

set(UBIT_CORE_FILES

	src/ubit.hpp
	src/ubit_features.h
	src/uappli.hpp
	src/uappliImpl.hpp
	src/uargs.hpp
	src/uargsImpl.hpp
	src/uattr.hpp
	src/ubackground.hpp
	src/uborder.hpp
	src/ubox.hpp
	src/uboxgeom.hpp
	src/uboxes.hpp
	src/ucall.hpp
	src/uchild.hpp
	src/uchoice.hpp
	src/uclass.hpp
	src/uclassImpl.hpp
	src/ucolor.hpp
	src/ucond.hpp
	src/uconf.hpp
	src/uctlmenu.hpp
	src/ucursor.hpp
	src/udata.hpp
	src/udefs.hpp
	src/udialogs.hpp
	src/udisp.hpp
	src/udoc.hpp
	src/udom.hpp
	src/uedit.hpp
	src/uelem.hpp
	src/uevent.hpp
	src/ueventflow.hpp
	src/ufile.hpp
	src/ufilebox.hpp
	src/ufont.hpp
	src/ufontImpl.hpp
	src/ufontmetrics.hpp
	src/ufinder.hpp
	src/ufinderImpl.hpp
	src/uflag.hpp
	src/ugeom.hpp
	src/ugl.hpp
	src/uglcanvas.hpp
	src/ugraph.hpp
	src/uhtml.hpp
	src/uicon.hpp
	src/uima.hpp
	src/uinteractors.hpp
	src/ukey.hpp
	src/ulength.hpp
	src/ulistbox.hpp
	src/umenu.hpp
	src/umenuImpl.hpp
	src/umessage.hpp
	src/umservice.hpp
	src/umsproto.hpp
	src/unode.hpp
	src/unumber.hpp
	src/uobject.hpp
	src/uon.hpp
	src/upalette.hpp
	src/uupdate.hpp
	src/uupdatecontext.hpp
	src/uparent.hpp
	src/upiemenu.hpp
	src/upix.hpp
	src/uselection.hpp
	src/uslider.hpp
	src/uscrollbar.hpp
	src/uscrollpane.hpp
	src/ustr.hpp
	src/ustyle.hpp
	src/ustyleparser.hpp
	src/usymbol.hpp
	src/usubwin.hpp
	src/usocket.hpp
	src/usource.hpp
	src/utable.hpp
	src/utimer.hpp
	src/utreebox.hpp
	src/uview.hpp
	src/uviewImpl.hpp
	src/uwin.hpp
	src/uwinImpl.hpp
	src/uxpm.hpp
	src/uxmlgrammar.hpp
	src/uxmlparser.hpp
	src/ucss.hpp
	src/uzoom.hpp
	src/u3d.hpp
	src/u3dicon.hpp
	src/nat/udispX11.hpp
	src/nat/udispGLUT.hpp
	src/nat/urendercontext.hpp
	src/nat/uglcontext.hpp
	src/nat/ux11context.hpp
	src/nat/uhardfont.hpp
	src/nat/uhardima.hpp
	src/nat/uhardwinX11.hpp
	src/nat/uhardwinGLUT.hpp

	src/uattr.cpp
	src/uappli.cpp
	src/uargs.cpp
	src/ubackground.cpp
	src/uborder.cpp
	src/ubox.cpp
	src/uboxgeom.cpp
	src/uboxes.cpp
	src/ucall.cpp
	src/uclass.cpp
	src/uchoice.cpp
	src/ucolor.cpp
	src/ucond.cpp
	src/uconf.cpp
	src/uctlmenu.cpp
	src/ucursor.cpp
	src/udisp.cpp
	src/udialogs.cpp
	src/udoc.cpp
	src/udom.cpp
	src/uedit.cpp
	src/uelem.cpp
	src/uevent.cpp
	src/ueventflow.cpp
	src/ufile.cpp
	src/ufilebox.cpp
	src/ufont.cpp
	src/ufontmetrics.cpp
	src/ufinder.cpp
	src/ufinderImpl.cpp
	src/uflag.cpp
	src/ugeom.cpp
	src/ugraph.cpp
	src/uglcanvas.cpp
	src/uhtml.cpp
	src/uicon.cpp
	src/uima.cpp
	src/uinteractors.cpp
	src/ulength.cpp
	src/ulistbox.cpp
	src/umenu.cpp
	src/umessage.cpp
	src/umservice.cpp
	src/unode.cpp
	src/unumber.cpp
	src/uobject.cpp
	src/uon.cpp
	src/upalette.cpp
	src/uupdate.cpp
	src/uupdatecontext.cpp
	src/upiemenu.cpp
	src/upix.cpp
	src/uselection.cpp
	src/ustr.cpp
	src/uslider.cpp
	src/uscrollbar.cpp
	src/uscrollpane.cpp
	src/usocket.cpp
	src/usource.cpp
	src/ustyle.cpp
	src/ustyleparser.cpp
	src/usymbol.cpp
	src/usubwin.cpp
	src/utable.cpp
	src/utimer.cpp
	src/utreebox.cpp
	src/uview.cpp
	src/uviewlayout.cpp
	src/uviewupdate.cpp
	src/uviewflow.cpp
	src/uwin.cpp
	src/uwinImpl.cpp
	src/uxpm.cpp
	src/uxmlgrammar.cpp
	src/uxmlparser.cpp
	src/ucss.cpp
	src/uzoom.cpp
	src/u3d.cpp
	src/u3dicon.cpp
	src/nat/udispX11.cpp
	src/nat/udispGLUT.cpp
	src/nat/uglcontext.cpp
	src/nat/ux11context.cpp
	src/nat/uhardfont.cpp
	src/nat/uhardima.cpp
	src/nat/uhardwinX11.cpp
	src/nat/uhardwinGLUT.cpp
	src/nat/uimaJPEG.cpp
	src/nat/uimaGIF.cpp
	src/nat/uimaXPM.cpp
	src/nat/ukeyX11.cpp
	src/nat/ukeyGLUT.cpp

)
