# This file is generated. Do not edit. Regenerate this with scripts/generate-cmake-files.js

set(UBIT_CORE_FILES

	src/ubit/ubit.hpp
	src/ubit/ubit_features.h
	src/ubit/uappli.hpp
	src/ubit/uappliImpl.hpp
	src/ubit/uargs.hpp
	src/ubit/uargsImpl.hpp
	src/ubit/uattr.hpp
	src/ubit/ubackground.hpp
	src/ubit/uborder.hpp
	src/ubit/ubox.hpp
	src/ubit/uboxgeom.hpp
	src/ubit/uboxes.hpp
	src/ubit/ucall.hpp
	src/ubit/uchild.hpp
	src/ubit/uchoice.hpp
	src/ubit/uclass.hpp
	src/ubit/uclassImpl.hpp
	src/ubit/ucolor.hpp
	src/ubit/ucond.hpp
	src/ubit/uconf.hpp
	src/ubit/uctlmenu.hpp
	src/ubit/ucursor.hpp
	src/ubit/udata.hpp
	src/ubit/udefs.hpp
	src/ubit/udialogs.hpp
	src/ubit/udisp.hpp
	src/ubit/udoc.hpp
	src/ubit/udom.hpp
	src/ubit/uedit.hpp
	src/ubit/uelem.hpp
	src/ubit/uevent.hpp
	src/ubit/ueventflow.hpp
	src/ubit/ufile.hpp
	src/ubit/ufilebox.hpp
	src/ubit/ufont.hpp
	src/ubit/ufontImpl.hpp
	src/ubit/ufontmetrics.hpp
	src/ubit/ufinder.hpp
	src/ubit/ufinderImpl.hpp
	src/ubit/uflag.hpp
	src/ubit/ugeom.hpp
	src/ubit/ugl.hpp
	src/ubit/uglcanvas.hpp
	src/ubit/ugraph.hpp
	src/ubit/uhtml.hpp
	src/ubit/uicon.hpp
	src/ubit/uima.hpp
	src/ubit/uinteractors.hpp
	src/ubit/ukey.hpp
	src/ubit/ulength.hpp
	src/ubit/ulistbox.hpp
	src/ubit/umenu.hpp
	src/ubit/umenuImpl.hpp
	src/ubit/umessage.hpp
	src/ubit/umservice.hpp
	src/ubit/umsproto.hpp
	src/ubit/unode.hpp
	src/ubit/unumber.hpp
	src/ubit/uobject.hpp
	src/ubit/uon.hpp
	src/ubit/upalette.hpp
	src/ubit/uupdate.hpp
	src/ubit/uupdatecontext.hpp
	src/ubit/uparent.hpp
	src/ubit/upiemenu.hpp
	src/ubit/upix.hpp
	src/ubit/uselection.hpp
	src/ubit/uslider.hpp
	src/ubit/uscrollbar.hpp
	src/ubit/uscrollpane.hpp
	src/ubit/ustr.hpp
	src/ubit/ustyle.hpp
	src/ubit/ustyleparser.hpp
	src/ubit/usymbol.hpp
	src/ubit/usubwin.hpp
	src/ubit/usocket.hpp
	src/ubit/usource.hpp
	src/ubit/utable.hpp
	src/ubit/utimer.hpp
	src/ubit/utreebox.hpp
	src/ubit/uview.hpp
	src/ubit/uviewImpl.hpp
	src/ubit/uwin.hpp
	src/ubit/uwinImpl.hpp
	src/ubit/uxpm.hpp
	src/ubit/uxmlgrammar.hpp
	src/ubit/uxmlparser.hpp
	src/ubit/ucss.hpp
	src/ubit/uzoom.hpp
	src/ubit/u3d.hpp
	src/ubit/u3dicon.hpp
	src/ubit/nat/udispX11.hpp
	src/ubit/nat/udispGLUT.hpp
	src/ubit/nat/urendercontext.hpp
	src/ubit/nat/uglcontext.hpp
	src/ubit/nat/ux11context.hpp
	src/ubit/nat/uhardfont.hpp
	src/ubit/nat/uhardima.hpp
	src/ubit/nat/uhardwinX11.hpp
	src/ubit/nat/uhardwinGLUT.hpp

	src/ubit/uattr.cpp
	src/ubit/uappli.cpp
	src/ubit/uargs.cpp
	src/ubit/ubackground.cpp
	src/ubit/uborder.cpp
	src/ubit/ubox.cpp
	src/ubit/uboxgeom.cpp
	src/ubit/uboxes.cpp
	src/ubit/ucall.cpp
	src/ubit/uclass.cpp
	src/ubit/uchoice.cpp
	src/ubit/ucolor.cpp
	src/ubit/ucond.cpp
	src/ubit/uconf.cpp
	src/ubit/uctlmenu.cpp
	src/ubit/ucursor.cpp
	src/ubit/udisp.cpp
	src/ubit/udialogs.cpp
	src/ubit/udoc.cpp
	src/ubit/udom.cpp
	src/ubit/uedit.cpp
	src/ubit/uelem.cpp
	src/ubit/uevent.cpp
	src/ubit/ueventflow.cpp
	src/ubit/ufile.cpp
	src/ubit/ufilebox.cpp
	src/ubit/ufont.cpp
	src/ubit/ufontmetrics.cpp
	src/ubit/ufinder.cpp
	src/ubit/ufinderImpl.cpp
	src/ubit/uflag.cpp
	src/ubit/ugeom.cpp
	src/ubit/ugraph.cpp
	src/ubit/uglcanvas.cpp
	src/ubit/uhtml.cpp
	src/ubit/uicon.cpp
	src/ubit/uima.cpp
	src/ubit/uinteractors.cpp
	src/ubit/ulength.cpp
	src/ubit/ulistbox.cpp
	src/ubit/umenu.cpp
	src/ubit/umessage.cpp
	src/ubit/umservice.cpp
	src/ubit/unode.cpp
	src/ubit/unumber.cpp
	src/ubit/uobject.cpp
	src/ubit/uon.cpp
	src/ubit/upalette.cpp
	src/ubit/uupdate.cpp
	src/ubit/uupdatecontext.cpp
	src/ubit/upiemenu.cpp
	src/ubit/upix.cpp
	src/ubit/uselection.cpp
	src/ubit/ustr.cpp
	src/ubit/uslider.cpp
	src/ubit/uscrollbar.cpp
	src/ubit/uscrollpane.cpp
	src/ubit/usocket.cpp
	src/ubit/usource.cpp
	src/ubit/ustyle.cpp
	src/ubit/ustyleparser.cpp
	src/ubit/usymbol.cpp
	src/ubit/usubwin.cpp
	src/ubit/utable.cpp
	src/ubit/utimer.cpp
	src/ubit/utreebox.cpp
	src/ubit/uview.cpp
	src/ubit/uviewlayout.cpp
	src/ubit/uviewupdate.cpp
	src/ubit/uviewflow.cpp
	src/ubit/uwin.cpp
	src/ubit/uwinImpl.cpp
	src/ubit/uxpm.cpp
	src/ubit/uxmlgrammar.cpp
	src/ubit/uxmlparser.cpp
	src/ubit/ucss.cpp
	src/ubit/uzoom.cpp
	src/ubit/u3d.cpp
	src/ubit/u3dicon.cpp
	src/ubit/nat/udispX11.cpp
	src/ubit/nat/udispGLUT.cpp
	src/ubit/nat/uglcontext.cpp
	src/ubit/nat/ux11context.cpp
	src/ubit/nat/uhardfont.cpp
	src/ubit/nat/uhardima.cpp
	src/ubit/nat/uhardwinX11.cpp
	src/ubit/nat/uhardwinGLUT.cpp
	src/ubit/nat/uimaJPEG.cpp
	src/ubit/nat/uimaGIF.cpp
	src/ubit/nat/uimaXPM.cpp
	src/ubit/nat/ukeyX11.cpp
	src/ubit/nat/ukeyGLUT.cpp

)
